sudo: required
dist: trusty

group: edge

# whitelist
branches:
  only:
    - master

language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update
    - sudo apt-get install pkg-config autoconf-archive autotools-dev libicu-dev libxml2-dev libbz2-dev zlib1g-dev
    - git clone https://github.com/LanguageMachines/ticcutils
    - cd ticcutils
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
    - git clone https://github.com/LanguageMachines/libfolia
    - cd libfolia
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
    - git clone https://github.com/LanguageMachines/uctodata
    - cd uctodata
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
    - git clone https://github.com/LanguageMachines/ucto
    - cd ucto
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
    - git clone https://github.com/LanguageMachines/timbl
    - cd timbl
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
    - git clone https://github.com/LanguageMachines/mbt
    - cd mbt
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
    - git clone https://github.com/LanguageMachines/frogdata
    - cd frogdata
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
    - git clone https://github.com/LanguageMachines/frog
    - cd frog
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
install:
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
script:
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib  && make check
